version: "3.9"

services:
  adrian-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: adrian-admin
    ports:
      - "4000:80"
    env_file:
      - .env
    restart: always
